/** @typedef {'active'|'blocked'|'suspended'|'review'} AdminUserStatus */

/**
 * Config global del cerebro (alinea con P2P + feature flags).
 * @typedef {{
 *   price: { basePrice: number, minPrice: number, maxPrice: number },
 *   rules: { requireMiningToSell: boolean, requireProfile: boolean, rewardsEnabled: boolean },
 *   order: { minOrderAmount: number, maxOrderAmount: number },
 *   limits: { maxOrdersPerUser: number, maxDailyOrders: number, maxWeeklyOrders: number, maxMonthlyOrders: number },
 *   volume: { maxBuyPerDay: number, maxSellPerDay: number },
 *   flags: { p2pEnabled: boolean, rewardsEnabled: boolean, maintenance: boolean },
 * }} AdminGlobalConfig
 */

/** @returns {import('./adminReducer.js').AdminState} */
export function buildInitialAdminState() {
  return {
    users: [
      {
        id: 'U-2041',
        email: 'alpha@demo.aigenesis',
        username: 'alpha_node',
        wallet: '0xAAA111bbbbccccddddeeeeffff00000001',
        referrerId: 'U-1000',
        status: 'active',
        accountEnabled: true,
        p2pBlocked: false,
        fundsFrozen: false,
        balances: { aig: 8820, usd: 12400.55 },
        network: { leg: 'L', volumeLeft: 42000, volumeRight: 38100 },
        rewards: { directPct: 11, binaryPct: 10, pendingPayout: 120.5 },
        history: [
          { ts: '2026-04-01 10:12', action: 'deposit', detail: 'USDT +500' },
          { ts: '2026-04-02 09:00', action: 'bonus', detail: 'Direct +44 AIG' },
        ],
      },
      {
        id: 'U-2042',
        email: 'beta@demo.aigenesis',
        username: 'beta_flow',
        wallet: '0xBBB222ccccddddeeeeffff0000000002',
        referrerId: 'U-2041',
        status: 'active',
        accountEnabled: true,
        p2pBlocked: false,
        fundsFrozen: false,
        balances: { aig: 2100, usd: 3200 },
        network: { leg: 'R', volumeLeft: 12000, volumeRight: 28000 },
        rewards: { directPct: 11, binaryPct: 10, pendingPayout: 32.1 },
        history: [{ ts: '2026-04-02 14:30', action: 'stake', detail: 'Lock 500 AIG' }],
      },
      {
        id: 'U-2043',
        email: 'gamma@demo.aigenesis',
        username: 'gamma_risk',
        wallet: '0xCCC333ddddeeeeffff00000000000003',
        referrerId: 'U-1000',
        status: 'review',
        accountEnabled: true,
        p2pBlocked: false,
        fundsFrozen: false,
        balances: { aig: 450, usd: 890 },
        network: { leg: 'L', volumeLeft: 2100, volumeRight: 800 },
        rewards: { directPct: 9, binaryPct: 8, pendingPayout: 0 },
        history: [],
      },
      {
        id: 'U-2044',
        email: 'delta@demo.aigenesis',
        username: 'delta_off',
        wallet: '0xDDD444eeeeffff000000000000000004',
        referrerId: 'U-2042',
        status: 'suspended',
        accountEnabled: false,
        p2pBlocked: true,
        fundsFrozen: true,
        balances: { aig: 0, usd: 0 },
        network: { leg: 'R', volumeLeft: 0, volumeRight: 0 },
        rewards: { directPct: 11, binaryPct: 10, pendingPayout: 0 },
        history: [{ ts: '2026-03-28 18:00', action: 'suspend', detail: 'Compliance hold' }],
      },
    ],
    p2pOrders: [
      {
        id: 'O-91001',
        userId: 'U-2041',
        side: 'buy',
        amount: 1200,
        price: 23.4,
        status: 'open',
        createdAt: '2026-04-02T11:20:00Z',
      },
      {
        id: 'O-91002',
        userId: 'U-2042',
        side: 'sell',
        amount: 500,
        price: 23.9,
        status: 'open',
        createdAt: '2026-04-02T12:05:00Z',
      },
      {
        id: 'O-91003',
        userId: 'U-2043',
        side: 'buy',
        amount: 200,
        price: 23.1,
        status: 'filled',
        createdAt: '2026-04-01T09:00:00Z',
      },
    ],
    withdrawals: [
      {
        id: 'W-44001',
        userId: 'U-2041',
        asset: 'USDT',
        amount: 800,
        status: 'pending',
        createdAt: '2026-04-02T15:00:00Z',
      },
      {
        id: 'W-44002',
        userId: 'U-2042',
        asset: 'USDT',
        amount: 200,
        status: 'pending',
        createdAt: '2026-04-02T16:10:00Z',
      },
      {
        id: 'W-44003',
        userId: 'U-2043',
        asset: 'USDT',
        amount: 150,
        status: 'rejected',
        createdAt: '2026-04-01T14:20:00Z',
      },
    ],
    /** Ledger unificado tesorería (vista admin); retiros sincronizan con `withdrawals` por id. */
    walletLedger: [
      {
        id: 'D-90001',
        type: 'deposit',
        userId: 'U-2041',
        asset: 'USDT',
        amount: 2500,
        status: 'approved',
        createdAt: '2026-04-01T09:15:00Z',
      },
      {
        id: 'D-90002',
        type: 'deposit',
        userId: 'U-2043',
        asset: 'USDT',
        amount: 400,
        status: 'pending',
        createdAt: '2026-04-03T10:00:00Z',
      },
      {
        id: 'W-44001',
        type: 'withdrawal',
        userId: 'U-2041',
        asset: 'USDT',
        amount: 800,
        status: 'pending',
        createdAt: '2026-04-02T15:00:00Z',
      },
      {
        id: 'W-44002',
        type: 'withdrawal',
        userId: 'U-2042',
        asset: 'USDT',
        amount: 200,
        status: 'pending',
        createdAt: '2026-04-02T16:10:00Z',
      },
      {
        id: 'W-44003',
        type: 'withdrawal',
        userId: 'U-2043',
        asset: 'USDT',
        amount: 150,
        status: 'rejected',
        createdAt: '2026-04-01T14:20:00Z',
      },
      {
        id: 'B-80001',
        type: 'bonus',
        userId: 'U-2041',
        asset: 'AIG',
        amount: 44,
        status: 'approved',
        createdAt: '2026-04-02T09:00:00Z',
      },
      {
        id: 'B-80002',
        type: 'bonus',
        userId: 'U-2042',
        asset: 'AIG',
        amount: 12.5,
        status: 'approved',
        createdAt: '2026-03-30T18:30:00Z',
      },
      {
        id: 'A-70001',
        type: 'adjustment',
        userId: 'U-2044',
        asset: 'USDT',
        amount: 50,
        status: 'pending',
        createdAt: '2026-04-02T11:45:00Z',
      },
      {
        id: 'A-70002',
        type: 'adjustment',
        userId: 'U-2041',
        asset: 'AIG',
        amount: 100,
        status: 'approved',
        createdAt: '2026-03-29T08:00:00Z',
      },
    ],
    globalConfig: {
      price: { basePrice: 23, minPrice: 22, maxPrice: 25 },
      rules: { requireMiningToSell: true, requireProfile: true, rewardsEnabled: true },
      order: { minOrderAmount: 10, maxOrderAmount: 100_000 },
      limits: { maxOrdersPerUser: 10, maxDailyOrders: 5, maxWeeklyOrders: 20, maxMonthlyOrders: 60 },
      volume: { maxBuyPerDay: 50_000, maxSellPerDay: 50_000 },
      flags: { p2pEnabled: true, rewardsEnabled: true, maintenance: false },
    },
    rewardSystemEnabled: true,
    marketPaused: false,
    securityLogs: [
      {
        id: 'SEC-9001',
        actor: 'operator@aigenesis',
        action: 'policy.p2p.update',
        ts: 'Hace 12 min',
        risk: 'low',
      },
      {
        id: 'SEC-9002',
        actor: 'system',
        action: 'ledger.snapshot',
        ts: 'Hace 28 min',
        risk: 'info',
      },
      {
        id: 'SEC-9003',
        actor: 'operator@aigenesis',
        action: 'user.suspend',
        ts: 'Hace 1 h',
        risk: 'medium',
      },
    ],
    blockedIps: [],
    ui: {
      toast: null,
      /** @type {Record<string, boolean>} */
      loading: {},
    },
  };
}
